name: Delete virtual tables

on:
  push:
    branches: [ main ]
    paths: [ virtual_tables/** ]

env:
  BIGEYE_CREDENTIALS: ${{ secrets.BIGEYE_API_CREDENTIALS }}
  BIGEYE_CONFIG: ${{ secrets.BIGEYE_API_CONFIGS }}

jobs:
   delete_virtual_tables:

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Verify Changed files
      uses: tj-actions/changed-files@v44
      id: verify-changed-files
      with:
        files: |
          virtual_tables/**/*.{yaml,yml}

    - name: Delete virtual tables
      if: steps.verify-changed-files.outputs.any_deleted == 'true'
      env:
        DELETED_FILES: ${{ steps.verify-changed-files.outputs.deleted_files }}    
      run: |
          python -m pip install --upgrade pip
          python -m pip install bigeye-cli
    
          echo "$BIGEYE_CONFIG" >> config.ini
          echo "$BIGEYE_CREDENTIALS" >> credentials.ini
          for file in ${DELETED_FILES}; do
            deleted_commit=$(git rev-list --max-count=1 --all -- "${file}")
            sname=$(git show "${deleted_commit}"^:"${file}" | yq '.source_name')
            tname=$(git show "${deleted_commit}"^:"${file}" | yq '.table_name')
            echo "Deleting virtual table ${tname} in source ${sname}"
            bigeye catalog delete-virtual-table --bigeye_conf credentials.ini --config_file config.ini --source_name "${sname}" --table_name "${tname}"
          done
          