name: Deploy templates

on:
  push:
    branches: [ main ]
    paths: [ templates/** ]

env:
  BIGEYE_CREDENTIALS: ${{ secrets.BIGEYE_API_CREDENTIALS }}
  BIGEYE_CONFIG: ${{ secrets.BIGEYE_API_CONFIGS }}

jobs:
   deploy_templates:

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Verify Changed files
      uses: tj-actions/changed-files@v44
      id: verify-changed-files
      with:
        files: |
          templates/*.{yaml,yml}

    - name: Deploy templates
      if: steps.verify-changed-files.outputs.any_changed == 'true'
      env:
        CHANGED_FILES: ${{ steps.verify-changed-files.outputs.all_changed_files }}    
      run: |
          python -m pip install --upgrade pip
          python -m pip install bigeye-cli
    
          echo "$BIGEYE_CONFIG" >> config.ini
          echo "$BIGEYE_CREDENTIALS" >> credentials.ini
          for file in ${CHANGED_FILES}; do
            echo "Creating schedule from ${file}"
            template_info=$(<"${file}")
            sname=$(echo "${template_info}" | yq '.source_name')
            template_name=$(echo "${template_info}" | yq '.cron')
            bigeye workspace upsert-template --bigeye_conf credentials.ini --config_file config.ini \
            --source_name "${sname}" \
            --name "${template_name}" \
            --returns "${returns}" 
          done
          