on:
  pull_request:


jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0

    - name: Verify Changed files
      uses: tj-actions/changed-files@v44
      id: verify-changed-files
      with:
        write_output_files: true
        json: true
        files: |
          schedules/*.{yaml,yml}

    - name: Post pending deletes       
      if: steps.verify-changed-files.outputs.any_deleted == 'true'
      env:
        DELETED_FILES: ${{ steps.verify-changed-files.outputs.deleted_files }}
        URL: ${{ github.event.pull_request.comments_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      run: |
          for file in ${DELETED_FILES}; do
            ls -lt .github/outputs/
            cat .github/outputs/deleted_files.json
            
            schedule_info=$(<"${file}")
            sname=$(echo "${schedule_info}" | yq '.schedule_name')
            curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data "{ \"body\": \"Schedule ${sname} will be deleted from Bigeye with this PR\" }"
          done

        
